facebook/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('main.urls')),
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('friends/', include('friending.urls')),
]

handler404 = 'main.views.handler404'

friending/urls.py
from django.urls import path
from django.http import HttpResponse

from .views import IndexView, GeneralView, UpdateView, DeleteView, RequestIndexView

app_name = 'friending'
urlpatterns = [
    path('<int:second_user_id>/friends', IndexView.as_view(), name='index'),
    path('<int:second_user_id>', GeneralView.as_view(), name='general'),
    path('<int:second_user_id>/update', UpdateView.as_view(), name='update'),
    path('<int:second_user_id>/delete', DeleteView.as_view(), name='delete'),
    path('requests', RequestIndexView.as_view(), name='requests'),
]

main/urls.py
from django.urls import path
from django.http import HttpResponse

from . import views
from .views import MainView, ProfileView, NewsfeedView

app_name = 'main'
urlpatterns = [
    path('', NewsfeedView.as_view(), name='newsfeed'),
    path('users/<int:second_user_id>', MainView.as_view(), name='main'),
    path('users/<int:second_user_id>/profile',
         ProfileView.as_view(), name='profile'),
]

users/urls.py
from django.urls import path
from .views import LoginView, RegisterView, LogoutView, SearchView, SearchDataView, ProfilePictureView, CoverPhotoView

app_name = 'users'
urlpatterns = [
    path('login', LoginView.as_view(), name='login'),
    path('register', RegisterView.as_view(), name='register'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('search', SearchView.as_view(), name='search'),
    path('search_data', SearchDataView.as_view(), name='search_data'),
    path('upload_profile',
         ProfilePictureView.as_view(), name='upload_profile'),
    path('upload_cover',
         CoverPhotoView.as_view(), name='upload_cover'),
]

main/models.py
from django.db import models

# Create your models here.

friending/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.http import JsonResponse
from .models import Friending
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from datetime import datetime
from users.models import AppUser


class IndexView(LoginRequiredMixin, View):
    def get(self, request, second_user_id):
        current_user = request.user
        second_user = get_object_or_404(AppUser, pk=second_user_id)
        all_friend_users = Friending.get_all_friend_users(second_user)
        data = AppUser.get_users_data(current_user, all_friend_users)
        return JsonResponse({'user_list': data})


class GeneralView(LoginRequiredMixin, View):
    # add friend
    def post(self, request, second_user_id):
        user = request.user
        second_user = get_object_or_404(AppUser, pk=second_user_id)
        state = Friending.get_state(user, second_user)
        if not state == Friending.State.non_friend:
            return JsonResponse({'error': 'Bad request'})
        # create Friending record with sent_user
        Friending.add_friend(user, second_user)
        return JsonResponse({'state': Friending.State.request_sent})

    def get(self, request, second_user_id):
        second_user = get_object_or_404(AppUser, pk=second_user_id)
        user = request.user
        state = Friending.get_state(user, second_user)
        return JsonResponse({'state': state})


class UpdateView(LoginRequiredMixin, View):
    # accept request
    def post(self, request, second_user_id):
        second_user = get_object_or_404(AppUser, pk=second_user_id)
        user = request.user
        state = Friending.get_state(user, second_user)
        if not state == Friending.State.request_received:
            return JsonResponse({'error': 'Bad request'})
        Friending.accept_request(user, second_user)
        return JsonResponse({'state': Friending.State.friend})


class DeleteView(LoginRequiredMixin, View):
    # accept request
    def post(self, request, second_user_id):
        second_user = get_object_or_404(AppUser, pk=second_user_id)
        user = request.user
        state = Friending.get_state(user, second_user)
        if state == Friending.State.non_friend:
            return JsonResponse({'error': 'Bad request'})
        Friending.delete(user, second_user)
        return JsonResponse({'state': Friending.State.non_friend})


class RequestIndexView(LoginRequiredMixin, View):
    def get(self, request):
        current_user = request.user
        all_friend_requests = Friending.get_friend_requests(current_user)
        data = AppUser.get_users_data(current_user, all_friend_requests)
        return JsonResponse({'user_list': data})

main/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.http import JsonResponse
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from users.models import AppUser
from friending.models import Friending
from helper.helper import MAIN_MODE_ENUM


"""
    1st-level views: main, search, newsfeed
    newsfeed_url, search_url: required at all 1st-level views
"""


class MainView(LoginRequiredMixin, View):
    def get(self, request, second_user_id):
        user = request.user
        data = {
            'mode': MAIN_MODE_ENUM.Profile,
            'current_user': {
                'full_name': user.__str__(),
                'id': user.id,
                'picture_mini': user.get_profile_picture_mini(),
            },
            'newsfeed_url': reverse('main:newsfeed', args=()),
            'search_url': reverse('users:search', args=()),
            'second_user_main_url': reverse('main:main', args=(second_user_id,)),
            'second_user_profile_url': reverse('main:profile', args=(second_user_id,)),
        }
        return render(request, 'main/main.html', data)


class NewsfeedView(LoginRequiredMixin, View):
    def get(self, request):
        user = request.user
        data = {
            'mode': MAIN_MODE_ENUM.Newsfeed,
            'current_user': {
                'full_name': user.__str__(),
                'id': user.id,
                'picture_mini': user.get_profile_picture_mini(),
            },
            'newsfeed_url': reverse('main:newsfeed', args=()),
            'newsfeed_data_url': reverse('posts:newsfeed_data', args=()),
            'search_url': reverse('users:search', args=()),
        }
        return render(request, 'main/main.html', data)


class ProfileView(LoginRequiredMixin, View):
    def get(self, request, second_user_id):
        current_user = request.user
        data = AppUser.get_profile_data(current_user, second_user_id)
        if not data:
            return JsonResponse({'error': 'Bad request.'})

        return JsonResponse({'profile': data})


def handler404(request, exception, template_name="404.html"):
    response = render(request, template_name, {})
    response.status_code = 404
    return response

users/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.conf import settings
# from .models import AppUser
from django.views import View
from django.conf import settings as conf_settings
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.forms import ModelForm
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from users.models import AppUser
from django.db import IntegrityError
from django.http import JsonResponse
from fuzzy_match import algorithims


class LoginView(View):
    def get(self, request):
        user = request.user
        if user.is_authenticated:
            return HttpResponseRedirect(reverse('main:main', args=(user.id,)))
        else:
            return render(request, 'users/login.html', {})

    def post(self, request):
        body = request.POST
        username, password = body['username'], body['password']
        user = authenticate(request, username=username, password=password)
        if user is None:
            messages.error(request, "Invalid username and/or password!")
            return render(request, 'users/login.html', {})
        else:
            login(request, user)
            return HttpResponseRedirect(reverse('main:main', args=(user.id,)))


class RegisterView(View):
    def post(self, request):
        body = request.POST
        print(request.POST)
        username, email, password = body['username'], body['email'], body['password']
        try:
            user = AppUser.objects.create_user(
                username, email, password, first_name=body['first_name'], last_name=body['last_name'])
        except IntegrityError:
            return JsonResponse({'error': 'Username already exists.'})

        login(request, user)
        return JsonResponse({'url': reverse('main:main', args=(user.id,))})


class LogoutView(LoginRequiredMixin, View):
    def post(self, request):
        logout(request)
        return HttpResponseRedirect(reverse('users:login'))


class SearchView(LoginRequiredMixin, View):
    def get(self, request):
        current_user = request.user
        print(request)
        query = request.GET.get('q')
        search_data_url = reverse("users:search_data", args=())
        search_url = reverse("users:search", args=())
        return render(request, 'main/main.html', {
            'mode': 'search',
            'current_user': current_user,
            'newsfeed_url': reverse('main:newsfeed', args=()),
            'search_url': search_url,
            'search_data_url': f'{search_data_url}?q={query}',
        })


class SearchDataView(LoginRequiredMixin, View):
    TRIGRAM_THRESHOLD = 0.2

    def get(self, request):
        current_user = request.user
        query = request.GET.get('q')
        all_users = AppUser.objects.all()
        satisfied_users = []
        for user in all_users:
            query_trigram_score = algorithims.trigram(
                f'{user.first_name} {user.last_name}', query)
            if query_trigram_score > self.TRIGRAM_THRESHOLD:
                user.query_trigram_score = query_trigram_score
                satisfied_users.append(user)
        sorted_users = sorted(
            satisfied_users, key=lambda x: x.query_trigram_score, reverse=True)
        data = AppUser.get_users_data(current_user, sorted_users)

        return JsonResponse({"user_list": data})


class ProfilePictureView(LoginRequiredMixin, View):
    def post(self, request):
        user = request.user
        user.profile_picture = request.FILES['image']
        user.save()
        return JsonResponse({'url': user.get_profile_picture_round()})


class CoverPhotoView(LoginRequiredMixin, View):
    def post(self, request):
        user = request.user
        user.cover_photo = request.FILES['image']
        user.save()
        return JsonResponse({'url': user.get_cover_photo()})

main/templates/main/components/_friending.html
{% load static %}

<div class="original-friending friending">
    <div class="friending-non-friend">
        <form name="add-friend" action="{% url 'friending:general' user.id %}" method="post">
            <button type="submit" class="btn btn-primary">
                <img class="invert" src="{% static 'posts/images/add-friend.png' %}" alt="">
                &nbsp;Add friend</button>
        </form>
    </div>

    <div class="friending-request-sent">
        <form name="cancel-request" action="{% url 'friending:delete' user.id %}" method="post">
            <button type="submit" class="btn btn-light negative cancel-button">
                <img src="{% static 'posts/images/cancel-request.png' %}" alt="">
                &nbsp;Cancel request</button>
        </form>
    </div>

    <div class="dropdown friending-request-received">
        <button type="button" class="btn btn-primary dropdown-toggle" id="dropdownMenuButton" data-bs-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            <img class="invert" src="{% static 'posts/images/befriend.png' %}" alt="">
            &nbsp;Respond</button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <form name="confirm-request" action="{% url 'friending:update' user.id %}" method="post">
                <button type="submit" class="btn btn-link btn-confirm dropdown-item">Confirm</button>
            </form>
            <form name="delete-request" action="{% url 'friending:delete' user.id %}" method="post">
                <button type="submit" class="btn btn-link btn-delete-request dropdown-item">Delete
                    request</button>
            </form>
        </div>
    </div>

    <div class="dropdown friending-friend">
        <button type="button" class="btn btn-light negative dropdown-toggle" id="dropdownMenuButton"
            data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img src="{% static 'posts/images/befriend.png' %}" alt="">
            &nbsp;Friends</button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <form name="unfriend" action="{% url 'friending:delete' user.id %}" method="post">
                <button type="submit" class="btn btn-link btn-confirm dropdown-item">Unfriend</button>
            </form>
        </div>
    </div>

</div>

main/templates/main/components/_user.html
<div class="original-user-template user-template p-3 mb-2 col-12 col-lg-6">
    <a name="pic" href="">
        <img name="profile-picture"
            src="https://res.cloudinary.com/dtgokkyl1/image/upload/c_fill,h_80,w_80/v1/media/profile_pictures/elizabeth_olsen_etrm8v.jpg"
            alt="">
    </a>
    <a name="name" href="#" class="mylink">Manh Tran</a>
</div>