facebook/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('main.urls')),
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('friends/', include('friending.urls')),
]

handler404 = 'main.views.handler404'

friending/urls.py
from django.urls import path
from django.http import HttpResponse

from .views import IndexView, GeneralView, UpdateView, DeleteView, RequestIndexView

app_name = 'friending'
urlpatterns = [
    path('<int:second_user_id>/friends', IndexView.as_view(), name='index'),
    path('<int:second_user_id>', GeneralView.as_view(), name='general'),
    path('<int:second_user_id>/update', UpdateView.as_view(), name='update'),
    path('<int:second_user_id>/delete', DeleteView.as_view(), name='delete'),
    path('requests', RequestIndexView.as_view(), name='requests'),
]

main/urls.py
from django.urls import path
from django.http import HttpResponse

from . import views
from .views import MainView, ProfileView, NewsfeedView

app_name = 'main'
urlpatterns = [
    path('', NewsfeedView.as_view(), name='newsfeed'),
    path('users/<int:second_user_id>', MainView.as_view(), name='main'),
    path('users/<int:second_user_id>/profile',
         ProfileView.as_view(), name='profile'),
]

posts/urls.py
from django.urls import path
from django.http import HttpResponse

from .views import GeneralView, PhotoDataView, EditView, UpdateView, DeleteView, \
    LikeView, UnlikeView
from .newsfeed_views import NewsfeedDataView

app_name = 'posts'

urlpatterns = [
    path('users/<int:second_user_id>/posts',
         GeneralView.as_view(), name='create_index'),
    path('<int:post_id>/edit', EditView.as_view(), name='edit'),
    path('<int:post_id>/update', UpdateView.as_view(), name='update'),
    path('<int:post_id>/delete', DeleteView.as_view(), name='delete'),
    path('photos/<int:photo_id>/data',
         PhotoDataView.as_view(), name='photo_data'),

    path('likes/<int:post_id>', LikeView.as_view(), name='like_create_index'),
    path('likes/<int:post_id>/delete', UnlikeView.as_view(), name='like_delete'),

    path('newsfeed_data', NewsfeedDataView.as_view(), name='newsfeed_data'),
]

users/urls.py
from django.urls import path
from .views import LoginView, RegisterView, LogoutView, SearchView, SearchDataView, ProfilePictureView, CoverPhotoView

app_name = 'users'
urlpatterns = [
    path('login', LoginView.as_view(), name='login'),
    path('register', RegisterView.as_view(), name='register'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('search', SearchView.as_view(), name='search'),
    path('search_data', SearchDataView.as_view(), name='search_data'),
    path('upload_profile',
         ProfilePictureView.as_view(), name='upload_profile'),
    path('upload_cover',
         CoverPhotoView.as_view(), name='upload_cover'),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.http import JsonResponse
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from users.models import AppUser
from friending.models import Friending
from helper.helper import MAIN_MODE_ENUM


"""
    1st-level views: main, search, newsfeed
    newsfeed_url, search_url: required at all 1st-level views
"""


class MainView(LoginRequiredMixin, View):
    def get(self, request, second_user_id):
        user = request.user
        data = {
            'mode': MAIN_MODE_ENUM.Profile,
            'current_user': {
                'full_name': user.__str__(),
                'id': user.id,
                'picture_mini': user.get_profile_picture_mini(),
            },
            'newsfeed_url': reverse('main:newsfeed', args=()),
            'search_url': reverse('users:search', args=()),
            'second_user_main_url': reverse('main:main', args=(second_user_id,)),
            'second_user_profile_url': reverse('main:profile', args=(second_user_id,)),
        }
        return render(request, 'main/main.html', data)


class NewsfeedView(LoginRequiredMixin, View):
    def get(self, request):
        user = request.user
        data = {
            'mode': MAIN_MODE_ENUM.Newsfeed,
            'current_user': {
                'full_name': user.__str__(),
                'id': user.id,
                'picture_mini': user.get_profile_picture_mini(),
            },
            'newsfeed_url': reverse('main:newsfeed', args=()),
            'newsfeed_data_url': reverse('posts:newsfeed_data', args=()),
            'search_url': reverse('users:search', args=()),
        }
        return render(request, 'main/main.html', data)


class ProfileView(LoginRequiredMixin, View):
    def get(self, request, second_user_id):
        current_user = request.user
        data = AppUser.get_profile_data(current_user, second_user_id)
        if not data:
            return JsonResponse({'error': 'Bad request.'})

        return JsonResponse({'profile': data})


def handler404(request, exception, template_name="404.html"):
    response = render(request, template_name, {})
    response.status_code = 404
    return response

main/templates/main/_newPost.html
{% load static %}
<div id="whole-new-post">
    <div class="row">
        <div id="new-post" class="col-10 offset-1">
            <form action="{% url 'posts:create_index' user.id %}" method="post">
                <div class="mb-3">
                    <textarea class="form-control mb-3" name="content" rows="3"
                        placeholder="What's on your mind"></textarea>
                    <input class="images-input" type="file" class="form-control" name="images" accept="image/*"
                        multiple="multiple" style="display: none;">
                    <button type="button" class="photo-button btn"
                        onclick="document.querySelector('#new-post .images-input').click();">
                        <i data-visualcompletion="css-img"> </i>
                        <span>Add
                            photos</span></button>
                    <div class="col-4 image-preview-template image-preview">
                        <img src="{% static 'posts/images/default-cover-photo.jpg' %}" alt="">
                        <div class="remove-image-container">
                            <button type="button" class="remove-image-button">
                                <i data-visualcompletion="css-img"></i>
                            </button>
                        </div>
                    </div>
                    <div class="image-box">
                        <div class="image-preview-parent">
                            <!-- <div class="col-4 image-preview">
                                <img src="{% static 'posts/images/default-cover-photo.jpg' %}" alt="">
                            </div>
                            <div class="col-4 image-preview">
                                <img src="{% static 'posts/images/default-cover-photo.jpg' %}" alt="">
                            </div> -->
                        </div>
                    </div>
                </div>
                <button type="submit" class="post-button btn btn-primary font-weight-bold" disabled>Make
                    a
                    Post!</button>
            </form>
            <div class="pop-up"></div>
        </div>
    </div>
</div>

main/templates/main/_newsfeed.html
<section id="section-newsfeed">

    <div id="newsfeed" class="row mx-0">
        <div class="post-container col-6 offset-3">
            <!-- ALL POSTS -->
            <div class="all-posts">
            </div>
            <!-- POSTS INFO -->
            <div class="row posts-info">
                <div class="display">
                    <div class="loading col-6 offset-3 text-muted">
                        <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
                        Loading...
                    </div>
                    <div class="no-more col-6 offset-3 py-4">
                        <div class="post-text text-muted small">
                            There are no more posts to show right now.</div>
                    </div>
                </div>
                <div class="non-display">
                    <div class="no-more col-6 offset-3 py-4">
                        <div class="post-text">
                            Add friend me to view my posts my friend!</div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>

main/templates/main/_photo.html
{% block content %}

<section id="section-photo">
    <div id="section-photo-content">
        <div id="photo-display">
            <div class="background">
            </div>
            <img class="image"
                src="https://res.cloudinary.com/dtgokkyl1/image/upload/v1/media/profile_pictures/casemiro_xwaave"
                alt="">
            <div class="remove-container">
                <button type="button" class="remove-button">
                    <i data-visualcompletion="css-img"></i>
                </button>
            </div>
        </div>
        <div id="photo-info">
            <div class="post-info">
                <a href="">
                    <img class="avatar" src="" alt="">
                </a>
                <div>
                    <div class="author">
                        <a href="" name="name">Manh Tran</a>
                    </div>
                    <div class="pub-date small text-muted" name="datetime">December 4, 2023 3:03 PM</div>
                </div>
            </div>
        </div>
        <div id="photo-chat">
            <div class="content">
            </div>
        </div>
    </div>
</section>

{% endblock %}

main/templates/main/_profile.html
<div id="hidden-info">
    {% include 'main/components/_friending.html' %}
    {% include 'main/components/_user.html' %}
</div>
{% load static %}

<section id="section-profile">
    {% include 'main/profile/_newPost.html' %}


    <section id="section-profile-main">
        <!-- COVER-PHOTO -->
        <div id="cover-photo">
            <img src="" alt="cover-photo">
            <div class="dropdown">
                <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">Update cover photo
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <form action="{% url 'users:upload_cover'  %}" method="post" enctype="multipart/form-data">
                        <div class="input-group mb-2">
                            <input type="file" class="form-control" name="file" accept="image/*">
                            <button type="submit" class="input-group-text" disabled>Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <!-- BASIC INFO: PROFILE PIC, INFO, FRIENDING -->
        <div id="basic-info">
            <div id="profile-picture">
                <div id="profile-picture-circle"></div>
                <img src="" alt="profile-picture">
                <div class="dropdown">
                    <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <form action="{% url 'users:upload_profile' %}" method="post" enctype="multipart/form-data">
                            <div class="input-group mb-2">
                                <input type="file" class="form-control" name="file" accept="image/*"
                                    multiple="multiple">
                                <button type="submit" class="input-group-text" disabled>Update</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div id="info">
                <div class="full-name"></div>
                <div class="num-friends">friends</div>
            </div>


        </div>

        <hr>
        <!-- SELECT -->
        <div class="myselect mb-3" name="section">
            <a class="posts click" href="#">Posts</a>
            <a class="disabled" href="#">About</a>
            <a name="friends" href="#">Friends</a>
            <a class="disabled" href="#">Photos</a>
            <a class="disabled" href="#">Videos</a>
            <a class="disabled" href="#">More</a>
        </div>
        <hr>

        <!-- SELECT-CONTENT -->
        <div class="myselect-content" name="section">
            <div class="section-posts row">
                <div id="overview" class="col-12 col-lg-5">
                </div>
                {% include 'main/profile/_posts.html' %}

            </div>
            <div class="section-about row"></div>
            <div name="friends" class="row">
                <div class="myselect mb-3" name="friends">
                    <a name="all-friends" class="active" href="{% url 'friending:index' user.id %}">All friends</a>
                    <a name="friend-requests" class="home-required" href="{% url 'friending:requests' %}">Friend
                        requests</a>
                </div>
                <div class="myselect-content" name="friends">
                    <div name="all-friends" class="row">

                    </div>
                    <div name="friend-requests" class="row"></div>
                </div>


            </div>
            <div class="section-photos row"></div>
            <div class="section-videos row"></div>
            <div class="section-more row"></div>
        </div>

    </section>

</section>

main/templates/main/_search.html
{% block content %}

<section id="section-search">
    <div id="section-search-content">
        <div id="search-panel">
            <div name="content">
                <div class="title">Search results</div>
                <hr>
                </hr>
                <div class="filter-title">Filters</div>
                <div class="select">
                    <a href="#">
                        <div class="select-people my-3">
                            <div class="round">
                                <i data-visualcompletion="css-img"> </i>
                            </div>
                            <span>People</span>
                        </div>
                    </a>
                </div>
            </div>
        </div>
        <div id="search-result">
            <div class="results">


            </div>
            <div class="no-more col-6 offset-3 py-4">
                <div class="post-text text-muted small">
                    There are no more results to show right now.</div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

main/templates/main/main.html
{% extends "base.html" %}

{% block title %}Facebook - Profile{% endblock %}

{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'main/stylesheets/components/userTemplate.css' %}">
<link rel="stylesheet" href="{% static 'main/stylesheets/components/friending.css' %}">
<link rel="stylesheet" href="{% static 'main/stylesheets/components/components.css' %}">
<link rel="stylesheet" href="{% static 'main/stylesheets/posts.css' %}">
<link rel="stylesheet" href="{% static 'main/stylesheets/profile.css' %}">
<link rel="stylesheet" href="{% static 'main/stylesheets/newsfeed.css' %}">
<link rel="stylesheet" href="{% static 'main/stylesheets/newPost.css' %}">
<link rel="stylesheet" href="{% static 'main/stylesheets/search.css' %}">
<link rel="stylesheet" href="{% static 'main/stylesheets/photo.css' %}">
<link rel="stylesheet" href="{% static 'main/stylesheets/main.css' %}">
{% endblock %}

{% block content %}

{% include 'main/_search.html' %}
{% include 'main/_profile.html' %}
{% include 'main/_newsfeed.html' %}
{% include 'main/_photo.html' %}

{% endblock %}

{% block script %}
<script type="module" src="{% static 'main/scripts/main.js' %}"></script>
{% endblock %}