facebook/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('main.urls')),
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('friends/', include('friending.urls')),
]

handler404 = 'main.views.handler404'

friending/urls.py
from django.urls import path
from django.http import HttpResponse

from .views import IndexView, GeneralView, UpdateView, DeleteView, RequestIndexView

app_name = 'friending'
urlpatterns = [
    path('<int:second_user_id>/friends', IndexView.as_view(), name='index'),
    path('<int:second_user_id>', GeneralView.as_view(), name='general'),
    path('<int:second_user_id>/update', UpdateView.as_view(), name='update'),
    path('<int:second_user_id>/delete', DeleteView.as_view(), name='delete'),
    path('requests', RequestIndexView.as_view(), name='requests'),
]

main/urls.py
from django.urls import path
from django.http import HttpResponse

from . import views
from .views import MainView, ProfileView, NewsfeedView

app_name = 'main'
urlpatterns = [
    path('', NewsfeedView.as_view(), name='newsfeed'),
    path('users/<int:second_user_id>', MainView.as_view(), name='main'),
    path('users/<int:second_user_id>/profile',
         ProfileView.as_view(), name='profile'),
]

posts/urls.py
from django.urls import path
from django.http import HttpResponse

from .views import GeneralView, PhotoDataView, EditView, UpdateView, DeleteView, \
    LikeView, UnlikeView
from .newsfeed_views import NewsfeedDataView

app_name = 'posts'

urlpatterns = [
    path('users/<int:second_user_id>/posts',
         GeneralView.as_view(), name='create_index'),
    path('<int:post_id>/edit', EditView.as_view(), name='edit'),
    path('<int:post_id>/update', UpdateView.as_view(), name='update'),
    path('<int:post_id>/delete', DeleteView.as_view(), name='delete'),
    path('photos/<int:photo_id>/data',
         PhotoDataView.as_view(), name='photo_data'),

    path('likes/<int:post_id>', LikeView.as_view(), name='like_create_index'),
    path('likes/<int:post_id>/delete', UnlikeView.as_view(), name='like_delete'),

    path('newsfeed_data', NewsfeedDataView.as_view(), name='newsfeed_data'),
]

users/urls.py
from django.urls import path
from .views import LoginView, RegisterView, LogoutView, SearchView, SearchDataView, ProfilePictureView, CoverPhotoView

app_name = 'users'
urlpatterns = [
    path('login', LoginView.as_view(), name='login'),
    path('register', RegisterView.as_view(), name='register'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('search', SearchView.as_view(), name='search'),
    path('search_data', SearchDataView.as_view(), name='search_data'),
    path('upload_profile',
         ProfilePictureView.as_view(), name='upload_profile'),
    path('upload_cover',
         CoverPhotoView.as_view(), name='upload_cover'),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager, User
from django.core.validators import RegexValidator
from .managers import CustomUserManager
from django.utils import timezone
from users.models import AppUser
from helper.helper import generate_sentence
from django.db.models.signals import pre_delete
from django.dispatch import receiver
from django.urls import reverse
from datetime import datetime
from django.db import connection
from helper import helper

# Create your models here.


class Post(models.Model):
    post_text = models.TextField()
    pub_datetime = models.DateTimeField(
        'datetime published', default=timezone.now, blank=True)
    author = models.ForeignKey(AppUser, on_delete=models.CASCADE)
    likes = models.ManyToManyField(AppUser, related_name='liked_post')

    @classmethod
    def make_post_object(cls, user):
        return Post(post_text=generate_sentence(), author=user)

    @classmethod
    def make_post(cls, user):
        Post(post_text=generate_sentence(), author=user).save()

    def get_info(self, user):
        data = {
            'id': self.id,
            'author': self.author.__str__(),
            'author_main_url': reverse('main:main', args=(self.author.id,)),
            'author_image': self.author.get_profile_picture_mini(),
            'pub_timestamp': datetime.timestamp(self.pub_datetime) * 1000,
            'post_text': self.post_text,
            'post_edit_url': reverse('posts:edit', args=(self.id,)) if self.author.id == user.id else '',
            'post_delete_url': reverse('posts:delete', args=(self.id,)) if self.author.id == user.id else '',
            'like_number': self.likes.count(),
            'like_state': self.likes.filter(id=user.id).exists(),
            'like_create_url': reverse('posts:like_create_index', args=(self.id,)),
            'like_delete_url': reverse('posts:like_delete', args=(self.id,)),
            'photos': [{
                'image_url': pt.get_post_image(),
                'link': reverse('posts:photo_data', args=(pt.id,)),
            } for pt in self.photo_set.all()],
        }
        return data

    """
        Retrive post data.
        For high performance, using following queryset methods when querying:
        Post.objects.select_related('author').prefetch_related('photo_set').prefetch_related('likes')
    """

    def get_post_data(self, user):
        author = self.author
        photos = self.photo_set.all()
        likes = self.likes.all()
        data = {
            'id': self.id,
            'author': author.__str__(),
            'author_main_url': reverse('main:main', args=(author.id,)),
            'author_image': author.get_profile_picture_mini(),
            'pub_timestamp': datetime.timestamp(self.pub_datetime) * 1000,
            'post_text': self.post_text,
            'post_edit_url': reverse('posts:edit', args=(self.id,)) if author.id == user.id else '',
            'post_delete_url': reverse('posts:delete', args=(self.id,)) if author.id == user.id else '',
            'like_number': len(likes),
            'like_state': user in likes,
            'like_create_url': reverse('posts:like_create_index', args=(self.id,)),
            'like_delete_url': reverse('posts:like_delete', args=(self.id,)),
            'photos': [{
                'image_url': photo.get_post_image(),
                'link': reverse('posts:photo_data', args=(photo.id,)),
            } for photo in photos],
        }
        return data

    @classmethod
    def get_friend_posts(cls, user, limit, offset):
        post_list = []

        # get all posts that belong to user's friends
        with connection.cursor() as cursor:
            cursor.execute(
                """
                    SELECT p.id as pid
                    FROM posts_post p INNER JOIN users_appuser u
                    ON author_id = u.id INNER JOIN friending_friending fr ON
                    (u.id=fr.second_id AND fr.first_id=%s OR fr.second_id=%s AND u.id=first_id) AND fr.state='FR'
                    ORDER BY p.pub_datetime DESC;
                """, [user.id, user.id]
            )
            columns = [col[0] for col in cursor.description]
            post_list = [dict(zip(columns, row)) for row in cursor.fetchall()]

        pid_list = []
        for post_data in post_list:
            pid_list.append(post_data['pid'])
        total_num = len(pid_list)
        next_offset = offset + limit if total_num > offset + limit else -1

        # get all posts' necessary data
        data = []
        for post in Post.objects.select_related('author').prefetch_related('photo_set').prefetch_related('likes')   \
                .filter(pk__in=pid_list).order_by('-pub_datetime')[offset:offset + limit]:
            data.append(post.get_post_data(user))

        return data, next_offset

    """
        FOR SEEDING
    """
    @classmethod
    def get_friend_post_ids(cls, user):
        post_list = []

        # get all posts that belong to user's friends
        with connection.cursor() as cursor:
            cursor.execute(
                """
                    SELECT p.id as pid
                    FROM posts_post p INNER JOIN users_appuser u
                    ON author_id = u.id INNER JOIN friending_friending fr ON
                    (u.id=fr.second_id AND fr.first_id=%s OR fr.second_id=%s AND u.id=first_id) AND fr.state='FR'
                    ORDER BY p.pub_datetime DESC;
                """, [user.id, user.id]
            )
            columns = [col[0] for col in cursor.description]
            post_list = [dict(zip(columns, row)) for row in cursor.fetchall()]

        pid_list = []
        for post_data in post_list:
            pid_list.append(post_data['pid'])
        return pid_list

    @classmethod
    def test(cls):
        kwargs = {'pk__in': [3, 2]}
        return Post.objects.prefetch_related('photo_set').prefetch_related('likes').filter(**kwargs)


def image_file_name(instance, filename):
    name, ext = filename.split('.')
    file_path = 'photos/user_{user_id}/{name}.{ext}'.format(
        user_id=instance.author.id, name=name, ext=ext)
    return file_path


class Photo(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(AppUser, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=image_file_name)
    pub_datetime = models.DateTimeField(
        'datetime published', default=timezone.now)

    def get_image(self, h, w):
        if self.image and 'upload/' in self.image.url:
            return self.image.url.replace('upload/', f'upload/c_fill,h_{h},w_{w}/')
        return ''

    def get_post_image(self):
        return self.get_image(193, 193)

    def get_full_image(self):
        return self.image.url if self.image else ''


@receiver(pre_delete, sender=Photo)
def delete_image(sender, instance, using, **kwargs):
    # instance.image.delete()
    pass

posts/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.http import JsonResponse
from .models import Post, Photo
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from datetime import datetime
from users.models import AppUser
from friending.models import Friending
from helper.helper import compress_image, MAIN_MODE_ENUM
import json

NUM_POSTS_LOAD = 8


class PhotoDataView(LoginRequiredMixin, View):
    def get(self, request, photo_id):
        current_user = request.user
        # authorization
        photo = get_object_or_404(Photo, pk=photo_id)
        state = Friending.get_state(current_user, photo.author)
        if state != Friending.State.self and state != Friending.State.friend:
            return JsonResponse({'error': 'Permission denied!'})

        author = photo.author
        data = {
            'author': author.__str__(),
            'author_main_url': reverse('main:main', args=(author.id,)),
            'author_image': author.get_profile_picture_mini(),
            'pub_timestamp': datetime.timestamp(photo.pub_datetime) * 1000,
            'full_url': photo.get_full_image(),
        }
        return JsonResponse({
            'photo': data,
        })


class GeneralView(LoginRequiredMixin, View):
    def post(self, request, second_user_id):
        # process post text
        user = request.user
        body = request.POST

        newPost = Post(post_text=body['content'], author=user)
        newPost.save()
        p = {
            'author': newPost.author.__str__(),
            'author_image': newPost.author.get_profile_picture_mini(),
            'pub_timestamp': datetime.timestamp(newPost.pub_datetime) * 1000,
            'post_text': newPost.post_text,
            'like_number': 0,
        }

        # process post images
        images = request.FILES.getlist('images')
        print(images)

        new_photos = []
        for oimage in images:
            img_content = compress_image(oimage)
            new_photo = Photo(author=user, post=newPost,
                              image=img_content)
            new_photo.save()
            new_photos.append({
                'image_url': new_photo.get_post_image(),
                'link': reverse('posts:photo_data', args=(new_photo.id,)),
            })
        p['photos'] = new_photos

        return JsonResponse({'new_post': p})

    # get posts of @second_user
    def get(self, request, second_user_id):
        user = request.user
        second_user = get_object_or_404(AppUser, pk=second_user_id)
        state = Friending.get_state(user, second_user)
        if state != Friending.State.self and state != Friending.State.friend:
            return JsonResponse({'error': 'Permission denied!'})

        offset = int(request.GET['offset'])

        posts = Post.objects.select_related('author').prefetch_related('photo_set').prefetch_related('likes')   \
            .filter(author_id=second_user_id).order_by(
            '-pub_datetime')

        total_num = len(posts)
        next_offset = offset + NUM_POSTS_LOAD if total_num > offset + NUM_POSTS_LOAD else -1

        data = [post.get_post_data(user)
                for post in posts[offset:offset + NUM_POSTS_LOAD]]
        return JsonResponse({'page': data, 'next_offset': next_offset})


class EditView(LoginRequiredMixin, View):
    def get(self, request, post_id):
        user = request.user
        post = get_object_or_404(Post, pk=post_id)
        if post.author.id != user.id:
            return JsonResponse({'error': 'Permission denied!'})
        data = {
            'post_id': post.id,
            'post_text': post.post_text,
            'post_update_url': reverse('posts:update', args=(post.id,)),
            'photos': [{
                'image_url': pt.get_post_image(),
                'id': pt.id,
            } for pt in post.photo_set.all()],
        }
        return JsonResponse({'post': data})


class UpdateView(LoginRequiredMixin, View):
    def post(self, request, post_id):
        user = request.user
        post = get_object_or_404(Post, pk=post_id)
        if post.author.id != user.id:
            return JsonResponse({'error': 'Permission denied!'})

        body = request.POST
        post.post_text = body['content']
        post.save()

        # remove old images
        for removed_photo_id in json.loads(body['removedPhotoIds']):
            photo = get_object_or_404(Photo, pk=removed_photo_id)
            photo.delete()

        # add new images
        images = request.FILES.getlist('images')
        print(images)

        for oimage in images:
            img_content = compress_image(oimage)
            new_photo = Photo(author=user, post=post,
                              image=img_content)
            new_photo.save()

        data = {
            'post_id': post.id,
            'post_text': post.post_text,
            'photos': [{
                'image_url': pt.get_post_image(),
                'link': reverse('posts:photo_data', args=(pt.id,)),
            } for pt in post.photo_set.all()],
        }
        return JsonResponse({'updated_post': data})


class DeleteView(LoginRequiredMixin, View):
    def post(self, request, post_id):
        user = request.user
        post = get_object_or_404(Post, pk=post_id)
        if post.author.id != user.id:
            return JsonResponse({'error': 'Permission denied!'})

        post.delete()

        return JsonResponse({'deleted_post_id': post_id})


class LikeView(LoginRequiredMixin, View):
    def post(self, request, post_id):
        user = request.user
        post = get_object_or_404(Post, pk=post_id)
        second_user = post.author
        state = Friending.get_state(user, second_user)
        if state != Friending.State.self and state != Friending.State.friend:
            return JsonResponse({'error': 'Permission denied!'})

        if post.likes.filter(id=user.id).exists():
            return JsonResponse({'error': 'Bad request!'})

        post.likes.add(user)

        return JsonResponse({
            'liked_users': post.likes.count(),
            'post_id': post.id,
        })


class UnlikeView(LoginRequiredMixin, View):
    def post(self, request, post_id):
        user = request.user
        post = get_object_or_404(Post, pk=post_id)
        second_user = post.author
        state = Friending.get_state(user, second_user)
        if state != Friending.State.self and state != Friending.State.friend:
            return JsonResponse({'error': 'Permission denied!'})

        if not post.likes.filter(id=user.id).exists():
            return JsonResponse({'error': 'Bad request!'})

        post.likes.remove(user)

        return JsonResponse({
            'liked_users': post.likes.count(),
            'post_id': post.id,
        })

posts/templates/posts/_homeMain.html
{% load static %}
<div id="hidden-info">
    <form class="index-form" action="{% url 'posts:create_index' user.id %}"></form>
</div>

<section class="content">
    <div id="cover-photo">

        <img src="{% if user.cover_photo %}{{ cover_url }}{% else %}
            {% static 'posts/images/default-cover-photo.jpg' %}{% endif %}" alt="cover-photo">
        <div class="dropdown">
            <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">Update cover photo
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <form action="{% url 'posts:upload_cover' user.id %}" method="post" enctype="multipart/form-data">
                    <div class="input-group mb-2">
                        <input type="file" class="form-control" name="file">
                        <button type="submit" class="input-group-text" disabled>Update</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div id="basic-info">
        <div id="profile-picture">
            <div id="profile-picture-circle"></div>
            <img src="{% if user.profile_picture %}{{ profile_url_round }}{% else %}
                {% static 'posts/images/default-profile-picture.jpg' %}{% endif %}" alt="profile-picture">
            <div class="dropdown">
                <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <form action="{% url 'posts:upload_profile' user.id %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="input-group mb-2">
                            <input type="file" class="form-control" name="file">
                            <button type="submit" class="input-group-text" disabled>Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div id="info">
            <div class="full-name">{{user.first_name}} {{user.last_name}}</div>
            <div class="num-friends">688 friends</div>
        </div>
    </div>
    <hr>
    <div id="section-select" class="mb-3">
        <a href="#">Posts</a>
        <a href="#">About</a>
        <a href="#">Friends</a>
        <a href="#">Photos</a>
        <a href="#">Videos</a>
        <a href="#">Reel</a>
        <a href="#">More</a>
    </div>
    <hr>

    <div class="row">
        <div id="overview" class="col-5">
            Intro
            <div style="height: 200px"></div>
        </div>
        <div id="posts" class="col-7">
            <div id="whole-new-post">
                <div class="row">
                    <div id="new-post" class="col-10 offset-1">
                        <form action="{% url 'posts:create_index' user.id %}" method="post">
                            <div class="mb-3">
                                <textarea class="form-control" name="content" rows="3"
                                    placeholder="What's on your mind"></textarea>
                            </div>
                            <button type="submit" class="btn btn-primary font-weight-bold" disabled>Make a
                                Post!</button>
                        </form>
                    </div>
                </div>
            </div>
            <div id="all-posts">

            </div>
            <div id="post-template" class="whole-post row">
                <div class="post col-10 offset-1">
                    <div class="post-info">
                        <img src="https://res.cloudinary.com/dtgokkyl1/image/upload/c_fill,h_40,w_40/v1/media/profile_pictures/casemiro_xwaave"
                            alt="">
                        <div>
                            <div class="author">Manh Tran</div>
                            <div class="pub-date small text-muted">December 4, 2023</div>
                        </div>
                    </div>
                    <div class="post-text small mt-2">
                        Today is Sunday April 23rd. Our big family, Mr Phung's descendants took a trip to our
                        hometown at Hao Lai town, Cap Tien Commune, Tien Lang district, Hai Phong city. This is
                        a honoured tradition of Vietnamese people where we as descendants visit our homeland,
                        pay tribute to ancestors during warm spring time of the year. </div>
                </div>
            </div>

            <div class="row">
                <div class="loading col-6 offset-3 text-muted">
                    <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
                    Loading...
                </div>
                <div class="no-more col-6 offset-3 py-4">
                    <div class="post-text text-muted small">
                        There are no more posts to show right now.</div>
                </div>
            </div>

        </div>
    </div>

</section>

posts/templates/posts/_profileMain.html
{% load static %}
<div id="hidden-info">
    <form class="index-form" action="{% url 'posts:create_index' user.id %}"></form>
</div>

<section class="content">
    <!-- COVER-PHOTO -->
    <div id="cover-photo">
        <img src="{% if user.cover_photo %}{{ cover_url }}{% else %}
            {% static 'posts/images/default-cover-photo.jpg' %}{% endif %}" alt="cover-photo">
        {% if current_user.id == user.id %}
        <div class="dropdown">
            <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">Update cover photo
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <form action="{% url 'posts:upload_cover' user.id %}" method="post" enctype="multipart/form-data">
                    <div class="input-group mb-2">
                        <input type="file" class="form-control" name="file">
                        <button type="submit" class="input-group-text" disabled>Update</button>
                    </div>
                </form>
            </div>
        </div>
        {% endif %}
    </div>

    <!-- BASIC INFO: PROFILE PIC, INFO, FRIENDING -->
    <div id="basic-info">
        <div id="profile-picture">
            <div id="profile-picture-circle"></div>
            <img src="{% if user.profile_picture %}{{ profile_url_round }}{% else %}
                {% static 'posts/images/default-profile-picture.jpg' %}{% endif %}" alt="profile-picture">
            {% if current_user.id == user.id %}
            <div class="dropdown">
                <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <form action="{% url 'posts:upload_profile' user.id %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="input-group mb-2">
                            <input type="file" class="form-control" name="file">
                            <button type="submit" class="input-group-text" disabled>Update</button>
                        </div>
                    </form>
                </div>
            </div>
            {% endif %}
        </div>
        <div id="info">
            <div class="full-name">{{user.first_name}} {{user.last_name}}</div>
            <div class="num-friends">{{num_friends}} friends</div>
        </div>
        <!-- FRIENDING -->
        {% include 'posts/_friending.html' %}

    </div>

    <hr>
    <!-- SELECT -->
    <div class="myselect mb-3" name="section">
        <a class="posts click" href="#">Posts</a>
        <a class="disabled" href="#">About</a>
        <a name="friends" href="#">Friends</a>
        <a class="disabled" href="#">Photos</a>
        <a class="disabled" href="#">Videos</a>
        <a class="disabled" href="#">Reel</a>
        <a class="disabled" href="#">More</a>
    </div>
    <hr>

    <!-- SELECT-CONTENT -->
    <div class="myselect-content" name="section">
        <div class="section-posts row">
            <div id="overview" class="col-5">
                Intro
                <div style="height: 200px"></div>
            </div>
            <div id="posts" class="col-7">
                {% if current_user.id == user.id %}
                <div id="whole-new-post">
                    <div class="row">
                        <div id="new-post" class="col-10 offset-1">
                            <form action="{% url 'posts:create_index' user.id %}" method="post">
                                <div class="mb-3">
                                    <textarea class="form-control" name="content" rows="3"
                                        placeholder="What's on your mind"></textarea>
                                </div>
                                <button type="submit" class="btn btn-primary font-weight-bold" disabled>Make a
                                    Post!</button>
                            </form>
                        </div>
                    </div>
                </div>
                {% endif %}

                <!-- ALL THE POSTS -->
                <div class="all-posts">
                </div>
                <div id="post-template" class="whole-post row">
                    <div class="post col-10 offset-1">
                        <div class="post-info">
                            <a href="{% url 'posts:profile' user.id %}">
                                <img src="https://res.cloudinary.com/dtgokkyl1/image/upload/c_fill,h_40,w_40/v1/media/profile_pictures/casemiro_xwaave"
                                    alt="">
                            </a>
                            <div>
                                <div class="author">
                                    <a href="{% url 'posts:profile' user.id %}">Manh Tran</a>
                                </div>
                                <div class="pub-date small text-muted">December 4, 2023</div>
                            </div>
                        </div>
                        <div class="post-text small mt-2">
                            Today is Sunday April 23rd. Our big family, Mr Phung's descendants took a trip to our
                            hometown at Hao Lai town, Cap Tien Commune, Tien Lang district, Hai Phong city. This is
                            a honoured tradition of Vietnamese people where we as descendants visit our homeland,
                            pay tribute to ancestors during warm spring time of the year. </div>
                    </div>
                </div>

                <div class="row posts-info">
                    <div class="display">
                        <div class="loading col-6 offset-3 text-muted">
                            <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
                            Loading...
                        </div>
                        <div class="no-more col-6 offset-3 py-4">
                            <div class="post-text text-muted small">
                                There are no more posts to show right now.</div>
                        </div>
                    </div>
                    <div class="non-display">
                        <div class="no-more col-6 offset-3 py-4">
                            <div class="post-text">
                                Add friend me to view my posts my friend!</div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <div class="section-about row"></div>
        <div name="friends" class="row">
            <div class="myselect mb-3" name="friends">
                <a name="all-friends" class="active" href="{% url 'friending:index' user.id %}">All friends</a>
                <a name="friend-requests" class="home-required" href="{% url 'friending:requests' %}">Friend
                    requests</a>
            </div>
            <div class="myselect-content" name="friends">
                <div name="all-friends" class="row">
                    <div class="user-template p-3 mb-2 col-6">
                        <a name="pic" href="">
                            <img name="profile-picture"
                                src="https://res.cloudinary.com/dtgokkyl1/image/upload/c_fill,h_80,w_80/v1/media/profile_pictures/elizabeth_olsen_etrm8v.jpg"
                                alt="">
                        </a>
                        <a name="name" href="#" class="mylink">Manh Tran</a>
                    </div>
                </div>
                <div name="friend-requests" class="row"></div>
            </div>


        </div>
        <div class="section-photos row"></div>
        <div class="section-videos row"></div>
        <div class="section-reel row"></div>
        <div class="section-more row"></div>
    </div>

</section>