facebook/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('main.urls')),
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('friends/', include('friending.urls')),
]

handler404 = 'main.views.handler404'

main/urls.py
from django.urls import path
from django.http import HttpResponse

from . import views
from .views import MainView, ProfileView, NewsfeedView

app_name = 'main'
urlpatterns = [
    path('', NewsfeedView.as_view(), name='newsfeed'),
    path('users/<int:second_user_id>', MainView.as_view(), name='main'),
    path('users/<int:second_user_id>/profile',
         ProfileView.as_view(), name='profile'),
]

posts/urls.py
from django.urls import path
from django.http import HttpResponse

from .views import GeneralView, PhotoDataView, EditView, UpdateView, DeleteView, \
    LikeView, UnlikeView
from .newsfeed_views import NewsfeedDataView

app_name = 'posts'

urlpatterns = [
    path('users/<int:second_user_id>/posts',
         GeneralView.as_view(), name='create_index'),
    path('<int:post_id>/edit', EditView.as_view(), name='edit'),
    path('<int:post_id>/update', UpdateView.as_view(), name='update'),
    path('<int:post_id>/delete', DeleteView.as_view(), name='delete'),
    path('photos/<int:photo_id>/data',
         PhotoDataView.as_view(), name='photo_data'),

    path('likes/<int:post_id>', LikeView.as_view(), name='like_create_index'),
    path('likes/<int:post_id>/delete', UnlikeView.as_view(), name='like_delete'),

    path('newsfeed_data', NewsfeedDataView.as_view(), name='newsfeed_data'),
]

users/urls.py
from django.urls import path
from .views import LoginView, RegisterView, LogoutView, SearchView, SearchDataView, ProfilePictureView, CoverPhotoView

app_name = 'users'
urlpatterns = [
    path('login', LoginView.as_view(), name='login'),
    path('register', RegisterView.as_view(), name='register'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('search', SearchView.as_view(), name='search'),
    path('search_data', SearchDataView.as_view(), name='search_data'),
    path('upload_profile',
         ProfilePictureView.as_view(), name='upload_profile'),
    path('upload_cover',
         CoverPhotoView.as_view(), name='upload_cover'),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.http import JsonResponse
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from users.models import AppUser
from friending.models import Friending
from helper.helper import MAIN_MODE_ENUM


"""
    1st-level views: main, search, newsfeed
    newsfeed_url, search_url: required at all 1st-level views
"""


class MainView(LoginRequiredMixin, View):
    def get(self, request, second_user_id):
        user = request.user
        data = {
            'mode': MAIN_MODE_ENUM.Profile,
            'current_user': {
                'full_name': user.__str__(),
                'id': user.id,
                'picture_mini': user.get_profile_picture_mini(),
            },
            'newsfeed_url': reverse('main:newsfeed', args=()),
            'search_url': reverse('users:search', args=()),
            'second_user_main_url': reverse('main:main', args=(second_user_id,)),
            'second_user_profile_url': reverse('main:profile', args=(second_user_id,)),
        }
        return render(request, 'main/main.html', data)


class NewsfeedView(LoginRequiredMixin, View):
    def get(self, request):
        user = request.user
        data = {
            'mode': MAIN_MODE_ENUM.Newsfeed,
            'current_user': {
                'full_name': user.__str__(),
                'id': user.id,
                'picture_mini': user.get_profile_picture_mini(),
            },
            'newsfeed_url': reverse('main:newsfeed', args=()),
            'newsfeed_data_url': reverse('posts:newsfeed_data', args=()),
            'search_url': reverse('users:search', args=()),
        }
        return render(request, 'main/main.html', data)


class ProfileView(LoginRequiredMixin, View):
    def get(self, request, second_user_id):
        current_user = request.user
        data = AppUser.get_profile_data(current_user, second_user_id)
        if not data:
            return JsonResponse({'error': 'Bad request.'})

        return JsonResponse({'profile': data})


def handler404(request, exception, template_name="404.html"):
    response = render(request, template_name, {})
    response.status_code = 404
    return response

main/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My amazing site{% endblock %}</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'main/stylesheets/base.css' %}">
    {% block css %}{% endblock %}
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-light sticky-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'posts:newsfeed_data' %}">
                <img src="{% static 'posts/images/fb-Logo.png' %}" alt="">
            </a>
            <div id="search-bar">
                <label for="search-input">
                    <div class="glass"><img src="{% static 'loupe.png' %}" alt=""></div>
                </label>
                <form id="search-form" action="{% url 'users:search_data' %}">
                    <div class="space"></div>
                    <input type="search" id="search-input" class="form-control" />
                </form>
            </div>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse me-auto" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li>
                        <div class="dropdown pic-dropdown">
                            <button class="btn  dropdown-toggle" type="button" id="dropdownMenuButton"
                                data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <img src="{{ current_user.picture_mini }}" alt="">
                                <div class="icon-container">
                                    <svg fill="currentColor" viewBox="0 0 16 16" width="1em" height="1em"
                                        class="x1lliihq x1k90msu x2h7rmj x1qfuztq x198g3q0 x1kpxq89 xsmyaan">
                                        <g fill-rule="evenodd" transform="translate(-448 -544)">
                                            <path fill-rule="nonzero"
                                                d="M452.707 549.293a1 1 0 0 0-1.414 1.414l4 4a1 1 0 0 0 1.414 0l4-4a1 1 0 0 0-1.414-1.414L456 552.586l-3.293-3.293z">
                                            </path>
                                        </g>
                                    </svg>
                                </div>
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <form action="{% url 'users:logout' %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit"
                                        class="btn btn-link btn-logout dropdown-item text-15">Logout</button>
                                </form>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <main id="main">
        <div id="vertical-nav">
            <div class="nav flex-column">

                <a class="nav-link newsfeed-link" href="{% url 'posts:newsfeed_data' %}">
                    <i class="child-centre" data-visualcompletion="css-img"></i>
                </a>
                <a class="nav-link profile-link" href="{% url 'main:main' current_user.id %}">
                    <img src="{{ current_user.picture_mini }}" class="child-centre" alt="">
                </a>
                <!--
                <li class="nav-item">
                    <a class="nav-link disabled" href="#">Video</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#">Game</a>
                </li> -->
            </div>
        </div>
        {% block content %}
        {% endblock %}
    </main>
    <!-- <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 mt-5 border-top">
        <p class="col-md-4 mb-0 text-muted">&copy; 2022 Company, Inc</p>

        <ul class="nav col-md-4 justify-content-end">
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
        </ul>
    </footer> -->

    <div id="base-popup"></div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/1.2.1/axios.min.js"></script>
    <script type="text/javascript">     window.CSRF_TOKEN = "{{ csrf_token }}";
        window.FRIENDING_STATE = {
            Self: 'SELF',
            NonFriend: 'NON-FRIEND',
            RequestSent: 'REQUEST-SENT',
            RequestReceived: 'REQUEST-RECEIVED',
            Friend: 'FRIEND',
        }

        window.currentUserId = "{{ current_user.id }}"
        window.mode = "{{ mode }}"
        window.searchDataUrl = "{{ search_data_url }}"
        window.searchUrl = "{{ search_url }}"
        window.secondUserMainUrl = "{{ second_user_main_url }}"
        window.secondUserProfileUrl = "{{ second_user_profile_url }}"
        window.newsfeedDataUrl = "{{ newsfeed_data_url }}"
        window.newsfeedUrl = "{{ newsfeed_url }}"


        // define ele.clearChildren()
        if (typeof Element.prototype.clearChildren === 'undefined') {
            Object.defineProperty(Element.prototype, 'clearChildren', {
                configurable: true,
                enumerable: false,
                value: function () {
                    while (this.firstChild) this.removeChild(this.lastChild);
                }
            });
        }
        if (typeof Element.prototype.displayBlock === 'undefined') {
            Object.defineProperty(Element.prototype, 'displayBlock', {
                configurable: true,
                enumerable: false,
                value: function () {
                    this.style.display = 'block'
                }
            });
        }
        if (typeof Element.prototype.displayNone === 'undefined') {
            Object.defineProperty(Element.prototype, 'displayNone', {
                configurable: true,
                enumerable: false,
                value: function () {
                    this.style.display = 'none'
                }
            });
        }

        // var script = document.createElement('script');
        // script.src = 'https://code.jquery.com/jquery-3.6.3.min.js'; // Check https://jquery.com/ for the current version
        // document.getElementsByTagName('head')[0].appendChild(script);
    </script>
    <script src="https://code.jquery.com/jquery-3.6.3.min.js" type="text/javascript"></script>

    <script type="module" src="{% static 'main/scripts/base.js' %}"></script>
    <script type="module" src="{% static 'main/scripts/search/search.js' %}"></script>

    {% block script %}{% endblock %}
</body>

</html>